name:                prolog-test-server
version:             0.1.0.0
# synopsis:
# description:
license:             BSD3
author:              Oliver Westphal
copyright:           2021 Oliver Westphal
# maintainer:
category:            Web
build-type:          Simple

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - scotty
  - wai
  - wai-extra
  - wl-pprint-text
  - transformers
  - text
  - utf8-string
  - prolog-programming-task

library:
  source-dirs: src
  # exposed-modules:
  #   - Example

executables:
  prolog-test-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - prolog-test-server

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
      - prolog-test-server
      - hspec
      - hspec-wai
      - hspec-wai-json
      - http-types
